# Generated by Django 4.2.6 on 2024-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'One week'), (1, 'یک ماه'), (2, 'دو ماه'), (3, 'سه ماه'), (6, 'شش ماه'), (12, 'دوازده ماه')], unique=True, verbose_name='نوع اشتراک'),
        ),
    ]
