# Generated by Django 4.2.6 on 2024-03-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_alter_preparedmaterialcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Customer phone number')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Customer name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Customer comment')),
                ('question1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Answer of question 1')),
                ('question2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Answer of question 2')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_survey', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'Customer survey',
                'verbose_name_plural': 'Customers surveys',
            },
        ),
    ]
