# Generated by Django 4.2.6 on 2024-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersurvey',
            options={'verbose_name': 'نظرسنجی مشتری', 'verbose_name_plural': 'نظرسنجی\u200cهای مشتریان'},
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='کامنت مشتری'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره تلفن مشتری'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='question1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='پاسخ سوال ۱'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='question2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='پاسخ سوال ۲'),
        ),
    ]
