# Generated by Django 4.2.6 on 2024-07-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_alter_customersurvey_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_activity', models.CharField(choices=[('catering', 'Catering'), ('iranian_restaurant', 'Iranian restaurant'), ('non_iranian_restaurant', 'Non Iranian restaurant'), ('coffee_shop', 'Coffee Shop'), ('cafe_restaurant', 'Cafe Restaurant')], max_length=25, verbose_name='Field of Activity')),
                ('work_experience', models.CharField(max_length=20, verbose_name='Work Experience')),
                ('work_shift', models.CharField(choices=[('morning ', 'Morning'), ('noon ', 'Noon'), ('night ', 'Night')], max_length=20, verbose_name='Work Shift')),
                ('number_of_staff', models.IntegerField(verbose_name='Number of staff')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('personnel_training', models.TextField(blank=True, null=True, verbose_name='Personnel Training Detail')),
                ('business_concerns', models.TextField(blank=True, null=True, verbose_name='Business Concerns Detail')),
                ('accounting_software', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accounting Software')),
                ('conduct_inventory_reconciliation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conduct Inventory Reconciliation')),
                ('has_control_cost_system', models.CharField(choices=[('yes ', 'بله'), ('no ', 'خیر')], max_length=5, verbose_name='Has Control Cost System')),
                ('has_book_of_regulations', models.CharField(choices=[('yes ', 'بله'), ('no ', 'خیر')], max_length=5, verbose_name='Has Book of Regulations')),
                ('has_tasks_written', models.CharField(choices=[('yes ', 'بله'), ('no ', 'خیر')], max_length=5, verbose_name='Has Tasks Written')),
                ('has_recipes_written', models.CharField(choices=[('yes ', 'بله'), ('no ', 'خیر')], max_length=5, verbose_name='Has Recipes Written')),
                ('has_instructions_written', models.CharField(choices=[('yes ', 'بله'), ('no ', 'خیر')], max_length=5, verbose_name='Has Instructions Written')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Counseling survey',
                'verbose_name_plural': 'Counselings surveys',
            },
        ),
    ]
