# Generated by Django 4.2.6 on 2024-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_counseling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counseling',
            options={'verbose_name': 'Counseling', 'verbose_name_plural': 'Counselings'},
        ),
        migrations.AlterField(
            model_name='counseling',
            name='work_shift',
            field=models.CharField(max_length=50, verbose_name='Work Shift'),
        ),
    ]
