# Generated by Django 4.2.6 on 2024-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_counseling_options_alter_counseling_work_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='field_of_activity',
            field=models.CharField(choices=[('catering', 'کترینگ'), ('iranian_restaurant', 'Iranian restaurant'), ('non_iranian_restaurant', 'Non Iranian restaurant'), ('coffee_shop', 'کافی شاپ'), ('cafe_restaurant', 'Cafe Restaurant')], max_length=25, verbose_name='Field of Activity'),
        ),
    ]
