# Generated by Django 4.2.6 on 2024-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Place name'),
        ),
    ]
