# Generated by Django 4.2.6 on 2024-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_name_userprofile_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='place_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام مجموعه'),
        ),
    ]
