# Generated by Django 4.2.6 on 2024-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_used_free_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_app_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
