# Generated by Django 4.2.6 on 2024-01-16 16:00

import apps.account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_access_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=8, null=True, verbose_name='Gender')),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[apps.account.validators.validate_didit_type], verbose_name='Melli code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/', verbose_name='Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'Users profile',
            },
        ),
    ]
