# Generated by Django 4.2.6 on 2024-07-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_has_seen_app_welcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_seen_app_welcome',
        ),
    ]
