# Generated by Django 4.2.6 on 2024-02-17 02:56

import apps.course.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('short_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه')),
                ('description', tinymce.models.HTMLField(default='', verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('in_person', 'حضوری'), ('online', 'سمینار'), ('offline', 'غیر حضوری')], default='offline', max_length=32, verbose_name='نوع دوره')),
                ('duration', models.CharField(help_text='۲ ساعت و ۳۰ دقیقه', max_length=128, verbose_name='مدت زمان')),
                ('payment_type', models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='نوع پرداخت')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('selling_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت فروش')),
                ('introduction_video', models.FileField(blank=True, null=True, upload_to=apps.course.utils.introduction_video_path, verbose_name='ویدیو معرفی')),
                ('introduction_image', models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر معرفی')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر کاور')),
                ('pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('name', models.CharField(default='بدون نام', max_length=128, verbose_name='نام مدرس')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='معرفی کوتاه')),
                ('image', models.ImageField(upload_to='images/instructors/', verbose_name='تصویر پروفایل')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='آدرس توییتر/x')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسین',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('is_finished', models.BooleanField(default=False, verbose_name='تمام شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دوره\u200c کاربر',
                'verbose_name_plural': 'دوره\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان جلسه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جلسه دوره',
                'verbose_name_plural': 'جلسات دوره',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('question', models.CharField(max_length=255, verbose_name='عنوان سوًال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان قسمت')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره قسمت')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.course.utils.course_video_path, verbose_name='فایل ویدیو')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=0, help_text='دقیقه', null=True, verbose_name='مدت زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.course', verbose_name='دوره')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت ها',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='مدرس'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('text', models.TextField(max_length=512)),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.course', verbose_name='دوره')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cهای دوره',
            },
        ),
    ]
