# Generated by Django 4.2.6 on 2024-01-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('short_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='نوع دوره')),
                ('duration', models.CharField(help_text='۲ ساعت و ۳۰ دقیقه', max_length=255, verbose_name='مدت زمان')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('selling_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت فروش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='تصویر')),
                ('pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('name', models.CharField(default='بدون نام', max_length=128, verbose_name='نام مدرس')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='معرفی کوتاه')),
                ('image', models.ImageField(upload_to='images/instructors/', verbose_name='تصویر پروفایل')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='آدرس توییتر/x')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسین',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان جلسه')),
                ('file', models.FileField(upload_to='files/video/courses/', verbose_name='فایل ویدیو')),
                ('duration', models.PositiveIntegerField(default=0, help_text='ثانیه', verbose_name='مدت زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جلسه دوره',
                'verbose_name_plural': 'جلسات دوره',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('question', models.CharField(max_length=255, verbose_name='عنوان سوًال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='مدرس'),
        ),
    ]
