# Generated by Django 4.2.6 on 2024-01-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='No title', max_length=128, verbose_name='Title')),
                ('short_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('free', 'Free'), ('cash', 'Cash')], default='cash', max_length=32, verbose_name='Course type')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds', verbose_name='Duration')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('selling_price', models.PositiveIntegerField(default=0, verbose_name='Selling price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('name', models.CharField(default='بدون نام', max_length=128, verbose_name='Instructor name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('image', models.ImageField(upload_to='images/instructors/', verbose_name='Profile pic')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='X/Twitter url')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website url')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='No title', max_length=255, verbose_name='Session title')),
                ('file', models.FileField(upload_to='files/video/courses/', verbose_name='Video file')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds', verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course session',
                'verbose_name_plural': 'Course sessions',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('question', models.CharField(max_length=255, verbose_name='Question title')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='Instructor'),
        ),
    ]
