# Generated by Django 4.2.6 on 2024-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=32, verbose_name='نوع دوره'),
        ),
    ]
