# Generated by Django 4.2.6 on 2024-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='دقیقه', null=True, verbose_name='مدت زمان'),
        ),
    ]
