# Generated by Django 4.2.6 on 2024-01-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='selling_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Selling price'),
        ),
    ]
