# Generated by Django 4.2.6 on 2024-01-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_price_alter_course_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرسین'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-id',), 'verbose_name': 'جلسه دوره', 'verbose_name_plural': 'جلسات دوره'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='2h, 30m', max_length=255, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='selling_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='نوع دوره'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='عنوان سوًال'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی کوتاه'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='images/instructors/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='بدون نام', max_length=128, verbose_name='نام مدرس'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس توییتر/x'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='ثانیه', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(upload_to='files/video/courses/', verbose_name='فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان جلسه'),
        ),
    ]
