# Generated by Django 4.2.6 on 2024-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_payment_type_alter_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'مجازی'), ('offline', 'غیر حضوری')], default='offline', max_length=32, verbose_name='نوع دوره'),
        ),
    ]
