# Generated by Django 4.2.6 on 2024-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_episode_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introduction_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='ویدیو معرفی'),
        ),
    ]
