# Generated by Django 4.2.6 on 2024-02-17 02:34

import apps.course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video url'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'سمینار'), ('offline', 'غیر حضوری')], default='offline', max_length=32, verbose_name='نوع دوره'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.course.utils.course_video_path, verbose_name='فایل ویدیو'),
        ),
    ]
