# Generated by Django 4.2.6 on 2024-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='۲ ساعت و ۳۰ دقیقه', max_length=255, verbose_name='مدت زمان'),
        ),
    ]
