# Generated by Django 4.2.6 on 2024-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_pinned_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
    ]
