# Generated by Django 4.2.6 on 2024-02-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_session_options_remove_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cهای دوره'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'قسمت', 'verbose_name_plural': 'قسمت ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, help_text='دقیقه', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='شماره قسمت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.session', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان قسمت'),
        ),
    ]
