# Generated by Django 4.2.6 on 2024-02-11 13:54

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_comment_options_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='۲ ساعت و ۳۰ دقیقه', max_length=128, verbose_name='مدت زمان'),
        ),
    ]
