# Generated by Django 4.2.6 on 2024-02-11 20:54

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_description_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
