# Generated by Django 4.2.6 on 2024-02-12 14:17

import apps.course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='course',
            name='introduction_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='Introduction image'),
        ),
        migrations.AddField(
            model_name='course',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.course.utils.introduction_video_path, verbose_name='Introduction video'),
        ),
    ]
