# Generated by Django 4.2.6 on 2024-02-15 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(default=0, help_text='به ازای هر واحد', verbose_name='قیمت')),
                ('use_for', models.CharField(blank=True, max_length=128, null=True, verbose_name='استفاده برای')),
                ('quantity_raw_press', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='مقدار استاندارد در هر پرس خام')),
                ('quantity_baked_press', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='مقدار استاندارد در هر پرس پخته')),
                ('delivery_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن تحویلی')),
                ('weight_loss_cleaning_usable', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='وزن کاهش یافته در اثر تمیز کردن (قابل استفاده)')),
                ('weight_loss_cleaning_unusable', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='وزن کاهش یافته در اثر تمیز کردن (غیرقابل استفاده)')),
                ('edible_cleaned_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن تمیز شده (قابل خوراک)')),
                ('weight_loss_baking', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='کاهش وزن در خلال پخت')),
                ('salable_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن قابل فروش (قابل استفاده)')),
                ('raw_usable_quantity_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده خام')),
                ('baked_usable_quantity_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده پخته شده')),
                ('raw_usable_quantity_cost_per_press', models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده خام در هر پرس')),
                ('baked_usable_quantity_cost_per_press', models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده پخته شده در هر پرس')),
                ('number_of_raw_use', models.PositiveIntegerField(default=0, verbose_name='تعداد مورد استفاده خام')),
                ('number_of_baked_use', models.PositiveIntegerField(default=0, verbose_name='تعداد مورد استفاده پخته')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('preparation', models.TextField(blank=True, null=True, verbose_name='طرز تهیه')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی')),
                ('factor', models.DecimalField(decimal_places=1, default=1.5, max_digits=3, verbose_name='ضریب عامل')),
                ('service_price', models.PositiveIntegerField(default=0, verbose_name='هزینه خدمات')),
                ('price_with_factor', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی با ضریب')),
                ('menu_price', models.PositiveIntegerField(default=0, verbose_name='قیمت درج در منو')),
                ('item_profit', models.IntegerField(default=0, verbose_name='سود آیتم')),
                ('food_cost', models.IntegerField(default=0, verbose_name='فود کاست')),
                ('number_sold', models.PositiveIntegerField(default=0, verbose_name='تعداد فروخته شده')),
                ('total_sales', models.BigIntegerField(default=0, verbose_name='مجموع فروخته شده')),
                ('total_cost', models.BigIntegerField(default=0, verbose_name='مجموع هزینه\u200cها')),
                ('total_profit', models.BigIntegerField(default=0, verbose_name='مجموع سود')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipes/', verbose_name='تصویر')),
                ('is_material', models.BooleanField(default=False, verbose_name='ماده است')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رسپی غذا',
                'verbose_name_plural': 'رسپی\u200cهای غذاها',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('services_fee', models.PositiveSmallIntegerField(default=5, verbose_name='هزینه خدمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران ها',
            },
        ),
        migrations.CreateModel(
            name='RecipesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_categories', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'دسته رسپی غذا',
                'verbose_name_plural': 'دسته بندی\u200cهای رسپی غذا',
            },
        ),
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='مقدار')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی')),
                ('prepared_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_materials', to='restaurant.recipe', verbose_name='ماده آماده شده')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_materials', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='restaurant.recipe', verbose_name='رسپی')),
            ],
            options={
                'verbose_name': 'ماده رسپی',
                'verbose_name_plural': 'مواد رسپی',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurant.recipescategory', verbose_name='دسته'),
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='دسته تست', max_length=128, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_categories', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'دسته بندی مواد اولیه',
                'verbose_name_plural': 'دسته بندی\u200cهای مواد اولیه',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='restaurant.rawmaterialcategory', verbose_name='دسته'),
        ),
    ]
