# Generated by Django 4.2.6 on 2024-02-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_material_categories', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'Prepared material category',
                'verbose_name_plural': 'Prepared material categories',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepared_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_recipes', to='restaurant.preparedmaterialcategory', verbose_name='Prepared category'),
        ),
    ]
