# Generated by Django 4.2.6 on 2024-01-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialcategory',
            options={'verbose_name': 'دسته بندی مواد اولیه', 'verbose_name_plural': 'دسته بندی\u200cهای مواد اولیه'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'رستوران', 'verbose_name_plural': 'رستوران ها'},
        ),
        migrations.AlterField(
            model_name='rawmaterialcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_categories', to='restaurant.restaurant', verbose_name='رستوران'),
        ),
        migrations.AlterField(
            model_name='rawmaterialcategory',
            name='title',
            field=models.CharField(default='دسته تست', max_length=128, verbose_name='عنوان'),
        ),
    ]
