# Generated by Django 4.2.6 on 2024-03-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_preparedmaterialcategory_recipe_prepared_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparedmaterialcategory',
            options={'verbose_name': 'دسته بندی آماده سازی\u200c\u200cها', 'verbose_name_plural': 'دسته بندی\u200cهای آماده سازی\u200cها'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepared_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_recipes', to='restaurant.preparedmaterialcategory', verbose_name='دسته ماده آماده شده'),
        ),
    ]
