# Generated by Django 4.2.6 on 2024-02-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_rawmaterialcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(default=0, help_text='Per a unit', verbose_name='قیمت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='restaurant.rawmaterialcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Raw material',
                'verbose_name_plural': 'Raw materials',
            },
        ),
    ]
