# Generated by Django 4.2.6 on 2024-02-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rawmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'ماده اولیه', 'verbose_name_plural': 'مواد اولیه'},
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='baked_usable_quantity_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost of baked usable quantity'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='baked_usable_quantity_cost_per_press',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost of baked usable quantity per press'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='delivery_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Delivery weight'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='edible_cleand_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Edible cleaned weight'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='number_of_baked_use',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of baked use'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='number_of_raw_use',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of raw use'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='quantity_baked_press',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Standard quantity per baked press'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='quantity_raw_press',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Standard quantity per raw press'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='raw_usable_quantity_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost of raw usable quantity'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='raw_usable_quantity_cost_per_press',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost of raw usable quantity per press'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='salable_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Salable weight(usable)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='use_for',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Use for'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='weight_loss_baking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Weight loss due to baking'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='weight_loss_cleaning_unusable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Weight loss due to cleaning(unusable)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='weight_loss_cleaning_usable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Weight loss due to cleaning(usable)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='restaurant.rawmaterialcategory', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Per unit', verbose_name='قیمت'),
        ),
    ]
