# Generated by Django 4.2.6 on 2024-02-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rawmaterial_use_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='edible_cleand_weight',
            new_name='edible_cleaned_weight',
        ),
    ]
