# Generated by Django 4.2.6 on 2024-07-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_restaurantprofile_ongoingcosts_fixedcosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='cost_of_raw_materials',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Cost raw materials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='restaurant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile', verbose_name='Restaurant profile'),
        ),
        migrations.AlterField(
            model_name='ongoingcosts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ongoingcosts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ongoingcosts',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='ongoingcosts',
            name='restaurant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile', verbose_name='Restaurant profile'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='food_cost',
            field=models.SmallIntegerField(verbose_name='فود کاست'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='tax',
            field=models.SmallIntegerField(default=0, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
