# Generated by Django 4.2.6 on 2024-07-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantprofile_cost_of_raw_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantprofile',
            options={'verbose_name': 'Restaurant profile', 'verbose_name_plural': 'Restaurant profiles'},
        ),
        migrations.CreateModel(
            name='IncomeAndCostsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('duration', models.SmallIntegerField()),
                ('number_of_seats', models.SmallIntegerField()),
                ('avg_purchase', models.PositiveIntegerField()),
                ('avg_seat_occupancy', models.SmallIntegerField()),
                ('restaurant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile', verbose_name='Restaurant profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
