# Generated by Django 4.2.6 on 2024-02-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_edible_cleand_weight_rawmaterial_edible_cleaned_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='use_price',
        ),
    ]
