# Generated by Django 4.2.6 on 2024-02-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_rawmaterial_use_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='baked_usable_quantity_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده پخته شده'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='baked_usable_quantity_cost_per_press',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده پخته شده در هر پرس'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='delivery_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن تحویلی'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='edible_cleaned_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن تمیز شده (قابل خوراک)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='number_of_baked_use',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مورد استفاده پخته'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='number_of_raw_use',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مورد استفاده خام'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='به ازای هر واحد', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_baked_press',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='مقدار استاندارد در هر پرس پخته'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_raw_press',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='مقدار استاندارد در هر پرس خام'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='raw_usable_quantity_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده خام'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='raw_usable_quantity_cost_per_press',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه مقدار قابل استفاده خام در هر پرس'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='salable_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن قابل فروش (قابل استفاده)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='use_for',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='استفاده برای'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='weight_loss_baking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='کاهش وزن در خلال پخت'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='weight_loss_cleaning_unusable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='وزن کاهش یافته در اثر تمیز کردن (غیرقابل استفاده)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='weight_loss_cleaning_usable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='وزن کاهش یافته در اثر تمیز کردن (قابل استفاده)'),
        ),
        migrations.CreateModel(
            name='RecipesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_categories', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'Food recipes category',
                'verbose_name_plural': 'Food recipes categories',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('preparation', models.TextField(blank=True, null=True, verbose_name='How to prepare')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipes/', verbose_name='تصویر')),
                ('is_material', models.BooleanField(default=False, verbose_name='Is material')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurant.recipescategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'Food recipe',
                'verbose_name_plural': 'Food recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Amount')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='Final price')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_materials', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='restaurant.recipes', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Recipe material',
                'verbose_name_plural': 'Recipe materials',
            },
        ),
    ]
