# Generated by Django 4.2.6 on 2024-02-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_rawmaterial_baked_usable_quantity_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipematerial',
            options={'verbose_name': 'ماده رسپی', 'verbose_name_plural': 'مواد رسپی'},
        ),
        migrations.AlterModelOptions(
            name='recipescategory',
            options={'verbose_name': 'دسته رسپی غذا', 'verbose_name_plural': 'دسته\u200cهای رسپی غذا'},
        ),
        migrations.AlterField(
            model_name='recipematerial',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='recipematerial',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('preparation', models.TextField(blank=True, null=True, verbose_name='طرز تهیه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipes/', verbose_name='تصویر')),
                ('is_material', models.BooleanField(default=False, verbose_name='ماده است')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurant.recipescategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'رسپی غذا',
                'verbose_name_plural': 'رسپی\u200cهای غذاها',
            },
        ),
        migrations.AlterField(
            model_name='recipematerial',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='restaurant.recipe', verbose_name='رسپی'),
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
