# Generated by Django 4.2.6 on 2024-02-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_recipematerial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipematerial',
            name='recipe_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_materials_set', to='restaurant.recipe', verbose_name='ماده رسپی'),
        ),
    ]
