# Generated by Django 4.2.6 on 2024-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_recipematerial_recipe_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
