# Generated by Django 4.2.6 on 2024-02-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_recipe_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipematerial',
            name='recipe_material',
        ),
    ]
