# Generated by Django 4.2.6 on 2024-02-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_recipematerial_recipe_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipematerial',
            name='prepared_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_materials', to='restaurant.recipe', verbose_name='Prepared material'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurant.recipescategory', verbose_name='دسته'),
        ),
    ]
