# Generated by Django 4.2.6 on 2024-02-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_recipematerial_prepared_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipematerial',
            name='prepared_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_materials', to='restaurant.recipe', verbose_name='Prepared material'),
        ),
    ]
