# Generated by Django 4.2.6 on 2024-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_recipescategory_options_recipe_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='factor',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=3, verbose_name='ضریب عامل'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_cost',
            field=models.IntegerField(default=0, verbose_name='فود کاست'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='item_profit',
            field=models.IntegerField(default=0, verbose_name='سود آیتم'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت درج در منو'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروخته شده'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price_with_factor',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی با ضریب'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='service_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه خدمات'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.BigIntegerField(default=0, verbose_name='مجموع هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_profit',
            field=models.BigIntegerField(default=0, verbose_name='مجموع سود'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_sales',
            field=models.BigIntegerField(default=0, verbose_name='مجموع فروخته شده'),
        ),
    ]
