# Generated by Django 4.2.6 on 2024-02-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0017_alter_recipe_factor_alter_recipe_food_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='services_fee',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='هزینه خدمات'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
