# Generated by Django 4.2.6 on 2024-02-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='callback_url',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, verbose_name='آدرس کال بک'),
        ),
    ]
