# Generated by Django 4.2.6 on 2024-02-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_callback_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_tracking_code',
            field=models.CharField(default='NA', max_length=128, verbose_name='کد رهگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='callback_url',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, verbose_name='آدرس بازگشت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payable_price',
            field=models.IntegerField(default=0, verbose_name='قیمت قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order', verbose_name='سفارش'),
        ),
    ]
