# Generated by Django 4.2.6 on 2024-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MOBILE_VERIFICATION_CODE', 'کد تاییدیه موبایل'), ('SUBSCRIPTION_END_WARNING', 'هشدار پایان اشتراک')], max_length=128, verbose_name='نوع اعلان'),
        ),
    ]
