# Generated by Django 4.2.6 on 2024-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexvideo',
            options={'verbose_name': 'ویدیو صفحه اصلی', 'verbose_name_plural': 'ویدیو صفحه اصلی'},
        ),
        migrations.AlterModelOptions(
            name='topbanner',
            options={'ordering': ('-id',), 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرهای صفحه اصلی'},
        ),
        migrations.AlterField(
            model_name='indexvideo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/index/', verbose_name='کاور ویدیو'),
        ),
        migrations.AlterField(
            model_name='indexvideo',
            name='video',
            field=models.FileField(upload_to='images/index/', verbose_name='فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک مرتبط'),
        ),
    ]
