# Generated by Django 4.2.6 on 2024-02-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_indexvideo_options_alter_topbanner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexvideo',
            options={'verbose_name': 'ویدیو صفحه اصلی', 'verbose_name_plural': 'ویدیوهای صفحه اصلی'},
        ),
    ]
